version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.16
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Golang Test
          command: |
            go test -v ./...

  deploy:
    docker:
      - image: google/cloud-sdk:404.0.0-alpine
    resource_class: medium
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Deploy To GAE
          command: |
            gcloud app deploy

workflows:
  deploy_to_gae_workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
